name: Run Daily Ingestion

on:
    push:
        branches:
            - main
    workflow_run:
        workflows: ["Run Daily Ingestion"]
        types:
            - completed
    schedule:
        - cron: '0 3 * * *' # Run daily at 3 AM UTC
    workflow_dispatch: 

jobs:
    ingest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install Ta-Lib
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential libta-lib0 libta-lib-dev
                pip install TA-Lib
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Set Up Google Cloud Credentials
              uses: google-github-actions/auth@v0
              with:
                credentials_json: ${{ secrets.GCS_KEY }}

            - name: Run Ingestion Script
              env:
                GOOGLE_APPLICATION_CREDENTIALS: ${{ steps['Set up Google Cloud Credentials'].outputs.credentials_file_path }}
              working-directory: ${{ github.workspace }}
              run: |
                python ingestion/master.py
