name: Run Daily Ingestion

on:
    push:
        branches:
            - main # Removed to prevent push-triggered runs; now only scheduled
    schedule:
        - cron: '0 3 * * *' # Run daily at 3 AM UTC

jobs:
    ingest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Set Up Python Environment
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            # Removed redundant pip upgrade step; handled in Install System and Python Dependencies

            - name: Cache Python dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

            - name: Install Python Dependencies
              run: |
                pip install -r requirements.txt
          


            - name: Set Up Google Cloud Credentials
              run: |
                echo "${{ secrets.GCS_KEY_BASE64 }}" | base64 --decode > ${{ github.workspace }}/gcs-key.json

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GCS_KEY_BASE64 }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
            - name: Run Ingestion Script
              env:
                FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
                POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
              working-directory: ${{ github.workspace }}
              run: |
                python ingestion/ingest_data.py

            - name: upload debug.log to GCS
              run: |
                if [ -f ingestion/debug.log ]; then
                  gsutil cp ingestion/debug.log gs://candlethrob-candata/logs/ingestion/debug_$(date +%F_%H-%M-%S).log
                else
                  echo "No debug.log file found."
                fi
