name: Run Daily Ingestion

on:
    push:
        branches:
            - main

    schedule:
        - cron: '0 3 * * *' # Run daily at 3 AM UTC

jobs:
    ingest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install Ta-Lib and Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential wget libtool autoconf automake pkg-config python3-dev libffi-dev
                wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
                tar -xzf ta-lib-0.4.0-src.tar.gz
                cd ta-lib
                ./configure --prefix=/usr
                make
                sudo make install
                cd ..
                rm -rf ta-lib-0.4.0-src.tar.gz
                export CFLAGS="-I/usr/local/include"
                export LDFLAGS="-L/usr/local/lib"
                pip install ta-lib
                pip install requirements.txt
          
            - name: Set Up Google Cloud Credentials
              id: auth
              uses: google-github-actions/auth@v0
              with:
                credentials_json: ${{ secrets.GCS_KEY }}

            - name: Run Ingestion Script
              env:
                GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
              working-directory: ${{ github.workspace }}
              run: |
                python ingestion/master.py
